### ISSUE TITLE
error: mov instruction format

### ISSUE THREAD

**Issue by JayceM6** [kubo/funchook#36] opened 2022-09-25 07:59 UTC
000007FEFD9BDEB0 | 48:8B05 31180500         | mov rax,qword ptr ds:[7FEFDA0F6E8]  

hook only copy instruction, is wrong

**Comment by kubo** [comment] 2022-09-26 01:25
> hook only copy instruction, is wrong

I cannot understand what you wrote. Could you explain that with more words?

* What is your environment such as OS, architecture, disassembler engine (distorm (default), capstone or zydis)
* What you did.
* What you expected.
* What you got.

The disassembled format ` mov rax,qword ptr ds:[7FEFDA0F6E8]` doesn't match any format of disassembler engines used by funchook.

**Comment by JayceM6** [comment] 2022-09-26 01:51
OS: Windows 10 x64
disassembler engine: zydis
48:8B05 31180500 | mov rax,qword ptr ds:[7FEFDA0F6E8]
31180500 is offset (next instruction), like jmp xxxxxxxx or call xxxxxxxx
funchook only copy this instruction, without fixed offset

**Comment by kubo** [comment] 2022-09-26 02:21
> funchook only copy this instruction, without fixed offset

As far as I checked, funchook fixed the offset.

assembly code to test it using GNU C compiler on linux:

```asm
	.p2align 4
	.globl	x86_64_read_rip_relative_mem
x86_64_read_rip_relative_mem:
	movq	1f(%rip),%rax
	ret

	.balign 8
1:
	.quad	0xdeadbeefcafebabe
```

funchook's debug.log
```
  Original Instructions:
    00007feba95af1f0 (07) 488b0501000000           MOV RAX, [RIP+0x1]
      ip-relative 00000001, absolute address= 00007feba95af1f8, offset=3, size=32
    00007feba95af1f7 (01) c3                       RET
...skip...
  Trampoline Instructions:
    00007feba95eb020 (07) 488b05d141fcff           MOV RAX, [RIP-0x3be2f]
    00007feba95eb027 (05) e9cb41fcff               JMP 0x7feba95af1f7
```
The machine code is same with yours except offset. `488b05????????`.
The original instruction reads memory at address `00007feba95af1f8`, which is `00007feba95af1f0 + 7 (size of the instruction) + 0x1 (offset)`.
The instruction copied to trampoline reads memory at same address `00007feba95af1f8`, which is `00007feba95eb020 + 7 (size of the instruction) - 0x3be2f (offset)`.

**Comment by kubo** [comment] 2022-09-26 02:34
```
000007FEFD9BDEB0 | 48:8B05 31180500 | mov rax,qword ptr ds:[7FEFDA0F6E8]
```
instruction address: 0x000007FEFD9BDEB0
offset: 0x00051831  (bytes are swapped to fix endian)
absolute address to be read: 7FEFDA0F6E8

```
instruction address + size of the instruction + offset --> absolute address to be read
0x7FEFD9BDEB0 + 7 + 0x51831 --> 0x7FEFDA0F6E8.
```

**Comment by JayceM6** [comment] 2022-09-26 02:47
Windows 10 x64 (x64 process)
original instruction
000007FEFD9BDEB0 | 48:8B05 31180500         | mov rax,qword ptr ds:[7FEFDA0F6E8]
000007FEFD9BDEB7 | C3                       | ret

copied instruction to trampoline, don't fixed
000007FEFDA21020 | 48:8B05 31180500         | mov rax,qword ptr ds:[7FEFDA72858]
000007FEFDA21027 | E9 8BCEF9FF              | jmp xxxxxx

**Comment by kubo** [comment] 2022-09-26 03:49
I don't think it depends on OS. Though, I'll check it on Windows later. (not soon...)

Just out of curious, what tool do you use to get the disassemble code. I'm not familiar with Windows tools.

**Comment by JayceM6** [comment] 2022-09-26 04:19
you can use windbg

**Comment by kubo** [comment] 2022-09-26 04:44
Thanks. The machine code format `48:8B05 31180500` is different from what I see in windbg: lower hexadecimal numbers, no delimiters such as `:` and ` `(space). Latest windbg might have been improved.

In https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/disassembly-window
![debug window](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/images/window-disassembly.png)

**Comment by JayceM6** [comment] 2022-09-26 06:03
machine code format doesn't matter.
use x64 windbg attach x64 process: [u kernelbase!GetCommandLineW]
friend, please, fix it.

**Comment by kubo** [comment] 2022-09-29 09:25
It works without the issue for me. Could you provide reproducible code?

My test code is https://github.com/kubo/funchook_issue_36/blob/master/issue_36.c. (This repository will be removed later.)

The offset in instruction starting with `488B05` was fixed. See https://github.com/kubo/funchook_issue_36/actions/runs/3149982438/jobs/5122235303#step:4:5.
```
original func: func_addr=00007FFA74574CC0, offset=2704033, read_addr=00007FFA74808F68
trampoline func: func_addr=00007FFA74861020, offset=-360639, read_addr=00007FFA74808F68
```

OS: Microsoft Windows Server 2022  10.0.20348  Datacenter
https://github.com/kubo/funchook_issue_36/actions/runs/3149982438/jobs/5122235303#step:1:3
Compiler: Visual Studio 17 2022
https://github.com/kubo/funchook_issue_36/actions/runs/3149982438/jobs/5122235303#step:3:14
Disassembler engine: zydis
https://github.com/kubo/funchook_issue_36/blob/246f02e95683e103a6a455c9aa24b84d9950b45f/CMakeLists.txt#L7

**Comment by JayceM6** [comment] 2022-09-30 04:39
I use your code (https://github.com/kubo/funchook_issue_36/blob/master/issue_36.c)
output
```
original func: func_addr=000007FEFD8BDEB0, offset=333873, read_addr=000007FEFD90F6E8
trampoline func: func_addr=000007FEFDB31020, offset=333873, read_addr=000007FEFDB82858
Assertion failed: original_read_addr == trampoline_read_addr, file main.cpp, line 39
```
assert(original_read_addr == trampoline_read_addr);              // assert failed

funchook's version is Release v1.1.0

**Comment by kubo** [comment] 2022-09-30 13:46
Could you use the latest commit of the master branch?
It might be fixed somewhere after v1.1.0.

**Comment by JayceM6** [comment] 2022-10-01 13:44
you are right, master brash is ok!

**Comment by kubo** [comment] 2022-10-02 09:11
Well, I don't know what commits fixed it.
* Changes in [C source code](https://github.com/kubo/funchook/tree/master/src) since v1.1.0 are only two. [One affects only Linux and macOS](https://github.com/kubo/funchook/commit/9fd8719bf535c893e0626b3662760cbef7984a47). [The other affects only arm64 CPU](https://github.com/kubo/funchook/commit/e480591033af24686951ffec1cf05dd1b104e778). Both aren't related to Windows 10 x64.
* Zydis version depended by funchook has not been changed since v1.1.0.
 
 I cannot check it in detail because I don't have Windows machine for development now.

Be that as it may, I'll release v1.1.1 from the master branch and close this.

**Comment by kubo** [comment] 2022-10-02 14:55
v1.1.0 was released.

**Closed by kubo** 2022-10-02 14:55 UTC
