### ISSUE TITLE
Unable to prepare more than one hook [Windows]

### ISSUE THREAD

**Issue by tnavda** [kubo/funchook#6] opened 2019-07-04 18:29 UTC
If you have multiple funchook_prepare, the first one is created, but the following ones are using the same entry->trampoline pointer.  While I agree you should be able to use a single page for multiple hooks it doesn't look like the code actually supports it.  

From the log
Enter funchook_prepare(0x40300000, 0x7ffb6cc01938, 0x7ffb6c9912e6)
Leave funchook_prepare(..., [0x402cb420->**0x403d2020**],...) => 0
Enter funchook_prepare(0x40310000, 0x7ffb6cc01948, 0x7ffb6c991449)
Leave funchook_prepare(..., [0x402cb5f0->**0x403d2020**],...) => 0
Enter funchook_prepare(0x40320000, 0x7ffb6cc01958, 0x7ffb6c99444b)
Leave funchook_prepare(..., [0x402cb7c0->**0x403d2020**],...) => 0

This might also explain when you try to destroy multiple funchoot_t's it results in memory read exceptions.  

You calculate the number of entries a page can contain, but from what I can tell only one entry is allocated.
`funchook_entry_t entries[1];`

In the code below there is a page available it uses it, but no where does it dictate that the trampoline should be adjusted to X bytes into the page.  Which results in overwriting the pointer of the previous prepare call().

//Forgive formatting, github markup was jacking up the new lines.
 `for (pl = page_list.next; pl != &page_list; pl = pl->next) {`

      for (i = 0; i < max_num_pages; i++) {
            if (!pl->used[i]) {
                page = (funchook_page_t *)((size_t)pl + (i + 1) * page_size);
                if (funchook_page_avail(funchook, page, 0, func, disp)) {
                    break;
                }
            }
        }
    }`

In the interim, after this call I just set page to NULL and let a new page get allocated for each prepare call.  

I don't mind submitting a pull request, but I'm not sure based on your design how you would prefer it to be fixed.

**Comment by kubo** [comment] 2019-07-07 12:42
Thanks for pointing the issue.

> If you have multiple funchook_prepare, the first one is created, but the following ones are using the same entry->trampoline pointer. 

Could you post a sample program to reproduce the issue?

The test program in this project checks multiple funchook_prepare as follows:
https://github.com/kubo/funchook/blob/116e502638c1d3f873d83042ad2352a96514307c/test/test_main.c#L293-L296
debug.log in my Windows machine:
```
Enter funchook_prepare(0x1ce9bea0000, 0x7ff6b7d35640, 0x7ff6b7d312c0)
Leave funchook_prepare(..., [0x7ffbbad01ae0->0x7ffbbb011020],...) => 0
Enter funchook_prepare(0x1ce9bea0000, 0x7ff6b7d35630, 0x7ff6b7d31310)
Leave funchook_prepare(..., [0x7ffbbac778a0->0x7ffbbb011068],...) => 0
```
The first(0x7ffbbb011020) and second(0x7ffbbb011068) trampoline pointers are not same.

> You calculate the number of entries a page can contain, but from what I can tell only one entry is allocated.
> `funchook_entry_t entries[1];`

No, it is an idiom. See [here](https://devblogs.microsoft.com/oldnewthing/20040826-00/?p=38043).

> In the code below there is a page available it uses it, but no where does it dictate that the trampoline should be adjusted to X bytes into the page. Which results in overwriting the pointer of the previous prepare call().

The following code adjusts the address of trampoline in a page.
https://github.com/kubo/funchook/blob/116e502638c1d3f873d83042ad2352a96514307c/src/funchook.c#L301
and
https://github.com/kubo/funchook/blob/116e502638c1d3f873d83042ad2352a96514307c/src/funchook.c#L329

By the way, the code you pointed [smells](https://en.wikipedia.org/wiki/Code_smell).
https://github.com/kubo/funchook/blob/116e502638c1d3f873d83042ad2352a96514307c/src/funchook_windows.c#L166-L168
This should be:
```c
                funchook_page_t *p = (funchook_page_t *)((size_t)pl + (i + 1) * page_size);
                if (funchook_page_avail(funchook, p, 0, func, disp)) {
                    page = p;
                    break;
```

**Comment by kubo** [comment] 2019-07-15 06:04
@tnavda Could you try the latest code?
I could not reproduce your issue but I found a bug when many functions were hooked at once.
I added [a test case](https://github.com/kubo/funchook/commit/3ab6b31d386846079974db5fdd69e830038a7982) and [fixed it](https://github.com/kubo/funchook/commit/6693357dcce784b7be3f38672e9c2b9b02ef96c9).

**Comment by kubo** [comment] 2019-09-20 11:47
Closed.
@tnavda Please open a new issue if this issue isn't fixed by [this commit](https://github.com/kubo/funchook/commit/6693357dcce784b7be3f38672e9c2b9b02ef96c9).

**Closed by kubo** 2019-09-20 11:47 UTC
